# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from openapi_client.api_client import ApiClient
from openapi_client.exceptions import (
    ApiTypeError,
    ApiValueError
)


class TrainingApi(object):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def assign_resource_to_training(self, project_uuid, training_version, **kwargs):  # noqa: E501
        """Assign a resource to the training  # noqa: E501

        Assign the specified resource to the training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.assign_resource_to_training(project_uuid, training_version, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param ResourceReferenceObject resource_reference_object: Resource that needs to be added
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Resource
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.assign_resource_to_training_with_http_info(project_uuid, training_version, **kwargs)  # noqa: E501

    def assign_resource_to_training_with_http_info(self, project_uuid, training_version, **kwargs):  # noqa: E501
        """Assign a resource to the training  # noqa: E501

        Assign the specified resource to the training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.assign_resource_to_training_with_http_info(project_uuid, training_version, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param ResourceReferenceObject resource_reference_object: Resource that needs to be added
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(Resource, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['project_uuid', 'training_version', 'resource_reference_object']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method assign_resource_to_training" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project_uuid' is set
        if ('project_uuid' not in local_var_params or
                local_var_params['project_uuid'] is None):
            raise ApiValueError("Missing the required parameter `project_uuid` when calling `assign_resource_to_training`")  # noqa: E501
        # verify the required parameter 'training_version' is set
        if ('training_version' not in local_var_params or
                local_var_params['training_version'] is None):
            raise ApiValueError("Missing the required parameter `training_version` when calling `assign_resource_to_training`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_uuid' in local_var_params:
            path_params['project_uuid'] = local_var_params['project_uuid']  # noqa: E501
        if 'training_version' in local_var_params:
            path_params['training_version'] = local_var_params['training_version']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'resource_reference_object' in local_var_params:
            body_params = local_var_params['resource_reference_object']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth']  # noqa: E501

        return self.api_client.call_api(
            '/project/{project_uuid}/training/{training_version}/resource', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Resource',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def create_training(self, project_uuid, **kwargs):  # noqa: E501
        """Create a new training  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_training(project_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: Project object that needs to be trained (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Training
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.create_training_with_http_info(project_uuid, **kwargs)  # noqa: E501

    def create_training_with_http_info(self, project_uuid, **kwargs):  # noqa: E501
        """Create a new training  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.create_training_with_http_info(project_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: Project object that needs to be trained (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(Training, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['project_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method create_training" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project_uuid' is set
        if ('project_uuid' not in local_var_params or
                local_var_params['project_uuid'] is None):
            raise ApiValueError("Missing the required parameter `project_uuid` when calling `create_training`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_uuid' in local_var_params:
            path_params['project_uuid'] = local_var_params['project_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth']  # noqa: E501

        return self.api_client.call_api(
            '/project/{project_uuid}/training', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Training',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def delete_assigned_resource_from_training(self, project_uuid, training_version, resource_uuid, **kwargs):  # noqa: E501
        """Remove a resource from the training  # noqa: E501

        Removes the assigned resource from the training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_assigned_resource_from_training(project_uuid, training_version, resource_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param str resource_uuid: UUID of the resource (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.delete_assigned_resource_from_training_with_http_info(project_uuid, training_version, resource_uuid, **kwargs)  # noqa: E501

    def delete_assigned_resource_from_training_with_http_info(self, project_uuid, training_version, resource_uuid, **kwargs):  # noqa: E501
        """Remove a resource from the training  # noqa: E501

        Removes the assigned resource from the training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.delete_assigned_resource_from_training_with_http_info(project_uuid, training_version, resource_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param str resource_uuid: UUID of the resource (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['project_uuid', 'training_version', 'resource_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method delete_assigned_resource_from_training" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project_uuid' is set
        if ('project_uuid' not in local_var_params or
                local_var_params['project_uuid'] is None):
            raise ApiValueError("Missing the required parameter `project_uuid` when calling `delete_assigned_resource_from_training`")  # noqa: E501
        # verify the required parameter 'training_version' is set
        if ('training_version' not in local_var_params or
                local_var_params['training_version'] is None):
            raise ApiValueError("Missing the required parameter `training_version` when calling `delete_assigned_resource_from_training`")  # noqa: E501
        # verify the required parameter 'resource_uuid' is set
        if ('resource_uuid' not in local_var_params or
                local_var_params['resource_uuid'] is None):
            raise ApiValueError("Missing the required parameter `resource_uuid` when calling `delete_assigned_resource_from_training`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_uuid' in local_var_params:
            path_params['project_uuid'] = local_var_params['project_uuid']  # noqa: E501
        if 'training_version' in local_var_params:
            path_params['training_version'] = local_var_params['training_version']  # noqa: E501
        if 'resource_uuid' in local_var_params:
            path_params['resource_uuid'] = local_var_params['resource_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = ['oauth']  # noqa: E501

        return self.api_client.call_api(
            '/project/{project_uuid}/training/{training_version}/resource/{resource_uuid}', 'DELETE',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_corpus_of_training_resource(self, project_uuid, training_version, resource_uuid, **kwargs):  # noqa: E501
        """Get the corpus of the resource  # noqa: E501

        Returns the corpus of the specified resource for this training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_corpus_of_training_resource(project_uuid, training_version, resource_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param str resource_uuid: UUID of the resource (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.get_corpus_of_training_resource_with_http_info(project_uuid, training_version, resource_uuid, **kwargs)  # noqa: E501

    def get_corpus_of_training_resource_with_http_info(self, project_uuid, training_version, resource_uuid, **kwargs):  # noqa: E501
        """Get the corpus of the resource  # noqa: E501

        Returns the corpus of the specified resource for this training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_corpus_of_training_resource_with_http_info(project_uuid, training_version, resource_uuid, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param str resource_uuid: UUID of the resource (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(str, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['project_uuid', 'training_version', 'resource_uuid']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_corpus_of_training_resource" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project_uuid' is set
        if ('project_uuid' not in local_var_params or
                local_var_params['project_uuid'] is None):
            raise ApiValueError("Missing the required parameter `project_uuid` when calling `get_corpus_of_training_resource`")  # noqa: E501
        # verify the required parameter 'training_version' is set
        if ('training_version' not in local_var_params or
                local_var_params['training_version'] is None):
            raise ApiValueError("Missing the required parameter `training_version` when calling `get_corpus_of_training_resource`")  # noqa: E501
        # verify the required parameter 'resource_uuid' is set
        if ('resource_uuid' not in local_var_params or
                local_var_params['resource_uuid'] is None):
            raise ApiValueError("Missing the required parameter `resource_uuid` when calling `get_corpus_of_training_resource`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_uuid' in local_var_params:
            path_params['project_uuid'] = local_var_params['project_uuid']  # noqa: E501
        if 'training_version' in local_var_params:
            path_params['training_version'] = local_var_params['training_version']  # noqa: E501
        if 'resource_uuid' in local_var_params:
            path_params['resource_uuid'] = local_var_params['resource_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['text/plain'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth']  # noqa: E501

        return self.api_client.call_api(
            '/project/{project_uuid}/training/{training_version}/resource/{resource_uuid}/corpus', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_training_by_version(self, project_uuid, training_version, **kwargs):  # noqa: E501
        """Find project training results by UUID  # noqa: E501

        Returns the training object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_training_by_version(project_uuid, training_version, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Training
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.get_training_by_version_with_http_info(project_uuid, training_version, **kwargs)  # noqa: E501

    def get_training_by_version_with_http_info(self, project_uuid, training_version, **kwargs):  # noqa: E501
        """Find project training results by UUID  # noqa: E501

        Returns the training object  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_training_by_version_with_http_info(project_uuid, training_version, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(Training, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['project_uuid', 'training_version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_training_by_version" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project_uuid' is set
        if ('project_uuid' not in local_var_params or
                local_var_params['project_uuid'] is None):
            raise ApiValueError("Missing the required parameter `project_uuid` when calling `get_training_by_version`")  # noqa: E501
        # verify the required parameter 'training_version' is set
        if ('training_version' not in local_var_params or
                local_var_params['training_version'] is None):
            raise ApiValueError("Missing the required parameter `training_version` when calling `get_training_by_version`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_uuid' in local_var_params:
            path_params['project_uuid'] = local_var_params['project_uuid']  # noqa: E501
        if 'training_version' in local_var_params:
            path_params['training_version'] = local_var_params['training_version']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth']  # noqa: E501

        return self.api_client.call_api(
            '/project/{project_uuid}/training/{training_version}', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Training',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def set_corpus_of_training_resource(self, project_uuid, training_version, resource_uuid, body, **kwargs):  # noqa: E501
        """Set the corpus of the resource  # noqa: E501

        Updates the corpus of the specified resource for this training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_corpus_of_training_resource(project_uuid, training_version, resource_uuid, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param str resource_uuid: UUID of the resource (required)
        :param str body: New or updated corpus as plain text (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.set_corpus_of_training_resource_with_http_info(project_uuid, training_version, resource_uuid, body, **kwargs)  # noqa: E501

    def set_corpus_of_training_resource_with_http_info(self, project_uuid, training_version, resource_uuid, body, **kwargs):  # noqa: E501
        """Set the corpus of the resource  # noqa: E501

        Updates the corpus of the specified resource for this training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.set_corpus_of_training_resource_with_http_info(project_uuid, training_version, resource_uuid, body, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param str resource_uuid: UUID of the resource (required)
        :param str body: New or updated corpus as plain text (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['project_uuid', 'training_version', 'resource_uuid', 'body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method set_corpus_of_training_resource" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project_uuid' is set
        if ('project_uuid' not in local_var_params or
                local_var_params['project_uuid'] is None):
            raise ApiValueError("Missing the required parameter `project_uuid` when calling `set_corpus_of_training_resource`")  # noqa: E501
        # verify the required parameter 'training_version' is set
        if ('training_version' not in local_var_params or
                local_var_params['training_version'] is None):
            raise ApiValueError("Missing the required parameter `training_version` when calling `set_corpus_of_training_resource`")  # noqa: E501
        # verify the required parameter 'resource_uuid' is set
        if ('resource_uuid' not in local_var_params or
                local_var_params['resource_uuid'] is None):
            raise ApiValueError("Missing the required parameter `resource_uuid` when calling `set_corpus_of_training_resource`")  # noqa: E501
        # verify the required parameter 'body' is set
        if ('body' not in local_var_params or
                local_var_params['body'] is None):
            raise ApiValueError("Missing the required parameter `body` when calling `set_corpus_of_training_resource`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_uuid' in local_var_params:
            path_params['project_uuid'] = local_var_params['project_uuid']  # noqa: E501
        if 'training_version' in local_var_params:
            path_params['training_version'] = local_var_params['training_version']  # noqa: E501
        if 'resource_uuid' in local_var_params:
            path_params['resource_uuid'] = local_var_params['resource_uuid']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in local_var_params:
            body_params = local_var_params['body']
        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['text/plain'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth']  # noqa: E501

        return self.api_client.call_api(
            '/project/{project_uuid}/training/{training_version}/resource/{resource_uuid}/corpus', 'PUT',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)

    def start_training_by_version(self, project_uuid, training_version, **kwargs):  # noqa: E501
        """Start the specified training  # noqa: E501

        Start the training process for the specified training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.start_training_by_version(project_uuid, training_version, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: Training
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        return self.start_training_by_version_with_http_info(project_uuid, training_version, **kwargs)  # noqa: E501

    def start_training_by_version_with_http_info(self, project_uuid, training_version, **kwargs):  # noqa: E501
        """Start the specified training  # noqa: E501

        Start the training process for the specified training  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.start_training_by_version_with_http_info(project_uuid, training_version, async_req=True)
        >>> result = thread.get()

        :param async_req bool: execute request asynchronously
        :param str project_uuid: UUID of the project (required)
        :param int training_version: Training version of the project (required)
        :param _return_http_data_only: response data without head status code
                                       and headers
        :param _preload_content: if False, the urllib3.HTTPResponse object will
                                 be returned without reading/decoding response
                                 data. Default is True.
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :return: tuple(Training, status_code(int), headers(HTTPHeaderDict))
                 If the method is called asynchronously,
                 returns the request thread.
        """

        local_var_params = locals()

        all_params = ['project_uuid', 'training_version']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        for key, val in six.iteritems(local_var_params['kwargs']):
            if key not in all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method start_training_by_version" % key
                )
            local_var_params[key] = val
        del local_var_params['kwargs']
        # verify the required parameter 'project_uuid' is set
        if ('project_uuid' not in local_var_params or
                local_var_params['project_uuid'] is None):
            raise ApiValueError("Missing the required parameter `project_uuid` when calling `start_training_by_version`")  # noqa: E501
        # verify the required parameter 'training_version' is set
        if ('training_version' not in local_var_params or
                local_var_params['training_version'] is None):
            raise ApiValueError("Missing the required parameter `training_version` when calling `start_training_by_version`")  # noqa: E501

        collection_formats = {}

        path_params = {}
        if 'project_uuid' in local_var_params:
            path_params['project_uuid'] = local_var_params['project_uuid']  # noqa: E501
        if 'training_version' in local_var_params:
            path_params['training_version'] = local_var_params['training_version']  # noqa: E501

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = ['oauth']  # noqa: E501

        return self.api_client.call_api(
            '/project/{project_uuid}/training/{training_version}', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Training',  # noqa: E501
            auth_settings=auth_settings,
            async_req=local_var_params.get('async_req'),
            _return_http_data_only=local_var_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=local_var_params.get('_preload_content', True),
            _request_timeout=local_var_params.get('_request_timeout'),
            collection_formats=collection_formats)
