# coding: utf-8

# flake8: noqa
"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.0.3
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.acoustic_model import AcousticModel
from openapi_client.models.acoustic_model_type import AcousticModelType
from openapi_client.models.audio import Audio
from openapi_client.models.audio_reference_object import AudioReferenceObject
from openapi_client.models.audio_reference_with_callback_object import AudioReferenceWithCallbackObject
from openapi_client.models.audio_status import AudioStatus
from openapi_client.models.binary_decode_object import BinaryDecodeObject
from openapi_client.models.binary_resource_object import BinaryResourceObject
from openapi_client.models.callback_method import CallbackMethod
from openapi_client.models.callback_object import CallbackObject
from openapi_client.models.create_project_object import CreateProjectObject
from openapi_client.models.data_prep_stats import DataPrepStats
from openapi_client.models.decode_message import DecodeMessage
from openapi_client.models.decode_task_reference import DecodeTaskReference
from openapi_client.models.language import Language
from openapi_client.models.project import Project
from openapi_client.models.resource import Resource
from openapi_client.models.resource_reference_object import ResourceReferenceObject
from openapi_client.models.resource_status import ResourceStatus
from openapi_client.models.resource_type import ResourceType
from openapi_client.models.training import Training
from openapi_client.models.training_status import TrainingStatus
from openapi_client.models.user import User
