# coding: utf-8

# flake8: noqa
"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from openapi_client.models.acoustic_model import AcousticModel
from openapi_client.models.acoustic_model_type import AcousticModelType
from openapi_client.models.audio import Audio
from openapi_client.models.audio_reference_object import AudioReferenceObject
from openapi_client.models.audio_status import AudioStatus
from openapi_client.models.binary_upload import BinaryUpload
from openapi_client.models.callback import Callback
from openapi_client.models.callback_method import CallbackMethod
from openapi_client.models.decoding import Decoding
from openapi_client.models.decoding_status import DecodingStatus
from openapi_client.models.language import Language
from openapi_client.models.project import Project
from openapi_client.models.project_creation import ProjectCreation
from openapi_client.models.resource import Resource
from openapi_client.models.resource_reference_object import ResourceReferenceObject
from openapi_client.models.resource_status import ResourceStatus
from openapi_client.models.resource_type import ResourceType
from openapi_client.models.training import Training
from openapi_client.models.training_stats import TrainingStats
from openapi_client.models.training_status import TrainingStatus
from openapi_client.models.user import User
