# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CreateProjectObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'name': 'str',
        'acoustic_model': 'str',
        'parent': 'str'
    }

    attribute_map = {
        'name': 'name',
        'acoustic_model': 'acoustic_model',
        'parent': 'parent'
    }

    def __init__(self, name=None, acoustic_model=None, parent=None):  # noqa: E501
        """CreateProjectObject - a model defined in OpenAPI"""  # noqa: E501

        self._name = None
        self._acoustic_model = None
        self._parent = None
        self.discriminator = None

        self.name = name
        self.acoustic_model = acoustic_model
        if parent is not None:
            self.parent = parent

    @property
    def name(self):
        """Gets the name of this CreateProjectObject.  # noqa: E501

        Name of the new project  # noqa: E501

        :return: The name of this CreateProjectObject.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CreateProjectObject.

        Name of the new project  # noqa: E501

        :param name: The name of this CreateProjectObject.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def acoustic_model(self):
        """Gets the acoustic_model of this CreateProjectObject.  # noqa: E501

        UUID of the acoustic model  # noqa: E501

        :return: The acoustic_model of this CreateProjectObject.  # noqa: E501
        :rtype: str
        """
        return self._acoustic_model

    @acoustic_model.setter
    def acoustic_model(self, acoustic_model):
        """Sets the acoustic_model of this CreateProjectObject.

        UUID of the acoustic model  # noqa: E501

        :param acoustic_model: The acoustic_model of this CreateProjectObject.  # noqa: E501
        :type: str
        """
        if acoustic_model is None:
            raise ValueError("Invalid value for `acoustic_model`, must not be `None`")  # noqa: E501

        self._acoustic_model = acoustic_model

    @property
    def parent(self):
        """Gets the parent of this CreateProjectObject.  # noqa: E501

        UUID of the optional parent project  # noqa: E501

        :return: The parent of this CreateProjectObject.  # noqa: E501
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this CreateProjectObject.

        UUID of the optional parent project  # noqa: E501

        :param parent: The parent of this CreateProjectObject.  # noqa: E501
        :type: str
        """

        self._parent = parent

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CreateProjectObject):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
