# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DecodeSession(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'session_uuid': 'str',
        'creation_timestamp': 'datetime',
        'status': 'DecodeSessionStatus',
        'decodings': 'list[DecodeAudio]'
    }

    attribute_map = {
        'session_uuid': 'session_uuid',
        'creation_timestamp': 'creation_timestamp',
        'status': 'status',
        'decodings': 'decodings'
    }

    def __init__(self, session_uuid=None, creation_timestamp=None, status=None, decodings=None):  # noqa: E501
        """DecodeSession - a model defined in OpenAPI"""  # noqa: E501

        self._session_uuid = None
        self._creation_timestamp = None
        self._status = None
        self._decodings = None
        self.discriminator = None

        if session_uuid is not None:
            self.session_uuid = session_uuid
        if creation_timestamp is not None:
            self.creation_timestamp = creation_timestamp
        if status is not None:
            self.status = status
        if decodings is not None:
            self.decodings = decodings

    @property
    def session_uuid(self):
        """Gets the session_uuid of this DecodeSession.  # noqa: E501


        :return: The session_uuid of this DecodeSession.  # noqa: E501
        :rtype: str
        """
        return self._session_uuid

    @session_uuid.setter
    def session_uuid(self, session_uuid):
        """Sets the session_uuid of this DecodeSession.


        :param session_uuid: The session_uuid of this DecodeSession.  # noqa: E501
        :type: str
        """

        self._session_uuid = session_uuid

    @property
    def creation_timestamp(self):
        """Gets the creation_timestamp of this DecodeSession.  # noqa: E501


        :return: The creation_timestamp of this DecodeSession.  # noqa: E501
        :rtype: datetime
        """
        return self._creation_timestamp

    @creation_timestamp.setter
    def creation_timestamp(self, creation_timestamp):
        """Sets the creation_timestamp of this DecodeSession.


        :param creation_timestamp: The creation_timestamp of this DecodeSession.  # noqa: E501
        :type: datetime
        """

        self._creation_timestamp = creation_timestamp

    @property
    def status(self):
        """Gets the status of this DecodeSession.  # noqa: E501


        :return: The status of this DecodeSession.  # noqa: E501
        :rtype: DecodeSessionStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this DecodeSession.


        :param status: The status of this DecodeSession.  # noqa: E501
        :type: DecodeSessionStatus
        """

        self._status = status

    @property
    def decodings(self):
        """Gets the decodings of this DecodeSession.  # noqa: E501


        :return: The decodings of this DecodeSession.  # noqa: E501
        :rtype: list[DecodeAudio]
        """
        return self._decodings

    @decodings.setter
    def decodings(self, decodings):
        """Sets the decodings of this DecodeSession.


        :param decodings: The decodings of this DecodeSession.  # noqa: E501
        :type: list[DecodeAudio]
        """

        self._decodings = decodings

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DecodeSession):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
