# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class Decoding(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uuid': 'str',
        'status': 'DecodingStatus',
        'transcripts': 'list[object]',
        'audio': 'Audio'
    }

    attribute_map = {
        'uuid': 'uuid',
        'status': 'status',
        'transcripts': 'transcripts',
        'audio': 'audio'
    }

    def __init__(self, uuid=None, status=None, transcripts=None, audio=None):  # noqa: E501
        """Decoding - a model defined in OpenAPI"""  # noqa: E501

        self._uuid = None
        self._status = None
        self._transcripts = None
        self._audio = None
        self.discriminator = None

        self.uuid = uuid
        self.status = status
        self.transcripts = transcripts
        self.audio = audio

    @property
    def uuid(self):
        """Gets the uuid of this Decoding.  # noqa: E501


        :return: The uuid of this Decoding.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Decoding.


        :param uuid: The uuid of this Decoding.  # noqa: E501
        :type: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def status(self):
        """Gets the status of this Decoding.  # noqa: E501


        :return: The status of this Decoding.  # noqa: E501
        :rtype: DecodingStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Decoding.


        :param status: The status of this Decoding.  # noqa: E501
        :type: DecodingStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def transcripts(self):
        """Gets the transcripts of this Decoding.  # noqa: E501


        :return: The transcripts of this Decoding.  # noqa: E501
        :rtype: list[object]
        """
        return self._transcripts

    @transcripts.setter
    def transcripts(self, transcripts):
        """Sets the transcripts of this Decoding.


        :param transcripts: The transcripts of this Decoding.  # noqa: E501
        :type: list[object]
        """
        if transcripts is None:
            raise ValueError("Invalid value for `transcripts`, must not be `None`")  # noqa: E501

        self._transcripts = transcripts

    @property
    def audio(self):
        """Gets the audio of this Decoding.  # noqa: E501


        :return: The audio of this Decoding.  # noqa: E501
        :rtype: Audio
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """Sets the audio of this Decoding.


        :param audio: The audio of this Decoding.  # noqa: E501
        :type: Audio
        """
        if audio is None:
            raise ValueError("Invalid value for `audio`, must not be `None`")  # noqa: E501

        self._audio = audio

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Decoding):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
