/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { Resource } from '../model/resource';
import { ResourceReferenceObject } from '../model/resourceReferenceObject';
import { Training } from '../model/training';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable({
  providedIn: 'root'
})
export class TrainingService {

    protected basePath = 'http://localhost:8080/api/v1';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Assign a resource to the training
     * Assign the specified resource to the training
     * @param projectUuid UUID of the project
     * @param trainingVersion Training version of the project
     * @param resourceReferenceObject Resource that needs to be added
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public assignResourceToTraining(projectUuid: string, trainingVersion: number, resourceReferenceObject?: ResourceReferenceObject, observe?: 'body', reportProgress?: boolean): Observable<Resource>;
    public assignResourceToTraining(projectUuid: string, trainingVersion: number, resourceReferenceObject?: ResourceReferenceObject, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Resource>>;
    public assignResourceToTraining(projectUuid: string, trainingVersion: number, resourceReferenceObject?: ResourceReferenceObject, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Resource>>;
    public assignResourceToTraining(projectUuid: string, trainingVersion: number, resourceReferenceObject?: ResourceReferenceObject, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (projectUuid === null || projectUuid === undefined) {
            throw new Error('Required parameter projectUuid was null or undefined when calling assignResourceToTraining.');
        }
        if (trainingVersion === null || trainingVersion === undefined) {
            throw new Error('Required parameter trainingVersion was null or undefined when calling assignResourceToTraining.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<Resource>(`${this.configuration.basePath}/project/${encodeURIComponent(String(projectUuid))}/training/${encodeURIComponent(String(trainingVersion))}/resource`,
            resourceReferenceObject,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a new training
     * 
     * @param projectUuid Project object that needs to be trained
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createTraining(projectUuid: string, observe?: 'body', reportProgress?: boolean): Observable<Training>;
    public createTraining(projectUuid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Training>>;
    public createTraining(projectUuid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Training>>;
    public createTraining(projectUuid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (projectUuid === null || projectUuid === undefined) {
            throw new Error('Required parameter projectUuid was null or undefined when calling createTraining.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<Training>(`${this.configuration.basePath}/project/${encodeURIComponent(String(projectUuid))}/training`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Remove a resource from the training
     * Removes the assigned resource from the training
     * @param projectUuid UUID of the project
     * @param trainingVersion Training version of the project
     * @param resourceUuid UUID of the resource
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteAssignedResourceFromTraining(projectUuid: string, trainingVersion: number, resourceUuid: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteAssignedResourceFromTraining(projectUuid: string, trainingVersion: number, resourceUuid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteAssignedResourceFromTraining(projectUuid: string, trainingVersion: number, resourceUuid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteAssignedResourceFromTraining(projectUuid: string, trainingVersion: number, resourceUuid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (projectUuid === null || projectUuid === undefined) {
            throw new Error('Required parameter projectUuid was null or undefined when calling deleteAssignedResourceFromTraining.');
        }
        if (trainingVersion === null || trainingVersion === undefined) {
            throw new Error('Required parameter trainingVersion was null or undefined when calling deleteAssignedResourceFromTraining.');
        }
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling deleteAssignedResourceFromTraining.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.configuration.basePath}/project/${encodeURIComponent(String(projectUuid))}/training/${encodeURIComponent(String(trainingVersion))}/resource/${encodeURIComponent(String(resourceUuid))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get the corpus of the resource
     * Returns the corpus of the specified resource for this training
     * @param projectUuid UUID of the project
     * @param trainingVersion Training version of the project
     * @param resourceUuid UUID of the resource
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public getCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public getCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public getCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (projectUuid === null || projectUuid === undefined) {
            throw new Error('Required parameter projectUuid was null or undefined when calling getCorpusOfTrainingResource.');
        }
        if (trainingVersion === null || trainingVersion === undefined) {
            throw new Error('Required parameter trainingVersion was null or undefined when calling getCorpusOfTrainingResource.');
        }
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling getCorpusOfTrainingResource.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.configuration.basePath}/project/${encodeURIComponent(String(projectUuid))}/training/${encodeURIComponent(String(trainingVersion))}/resource/${encodeURIComponent(String(resourceUuid))}/corpus`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find project training results by UUID
     * Returns the training object
     * @param projectUuid UUID of the project
     * @param trainingVersion Training version of the project
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getTrainingByVersion(projectUuid: string, trainingVersion: number, observe?: 'body', reportProgress?: boolean): Observable<Training>;
    public getTrainingByVersion(projectUuid: string, trainingVersion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Training>>;
    public getTrainingByVersion(projectUuid: string, trainingVersion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Training>>;
    public getTrainingByVersion(projectUuid: string, trainingVersion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (projectUuid === null || projectUuid === undefined) {
            throw new Error('Required parameter projectUuid was null or undefined when calling getTrainingByVersion.');
        }
        if (trainingVersion === null || trainingVersion === undefined) {
            throw new Error('Required parameter trainingVersion was null or undefined when calling getTrainingByVersion.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Training>(`${this.configuration.basePath}/project/${encodeURIComponent(String(projectUuid))}/training/${encodeURIComponent(String(trainingVersion))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Set the corpus of the resource
     * Updates the corpus of the specified resource for this training
     * @param projectUuid UUID of the project
     * @param trainingVersion Training version of the project
     * @param resourceUuid UUID of the resource
     * @param body New or updated corpus as plain text
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public setCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, body: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public setCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, body: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public setCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, body: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public setCorpusOfTrainingResource(projectUuid: string, trainingVersion: number, resourceUuid: string, body: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (projectUuid === null || projectUuid === undefined) {
            throw new Error('Required parameter projectUuid was null or undefined when calling setCorpusOfTrainingResource.');
        }
        if (trainingVersion === null || trainingVersion === undefined) {
            throw new Error('Required parameter trainingVersion was null or undefined when calling setCorpusOfTrainingResource.');
        }
        if (resourceUuid === null || resourceUuid === undefined) {
            throw new Error('Required parameter resourceUuid was null or undefined when calling setCorpusOfTrainingResource.');
        }
        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling setCorpusOfTrainingResource.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'text/plain'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.put<any>(`${this.configuration.basePath}/project/${encodeURIComponent(String(projectUuid))}/training/${encodeURIComponent(String(trainingVersion))}/resource/${encodeURIComponent(String(resourceUuid))}/corpus`,
            body,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Start the specified training
     * Start the training process for the specified training
     * @param projectUuid UUID of the project
     * @param trainingVersion Training version of the project
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public startTrainingByVersion(projectUuid: string, trainingVersion: number, observe?: 'body', reportProgress?: boolean): Observable<Training>;
    public startTrainingByVersion(projectUuid: string, trainingVersion: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Training>>;
    public startTrainingByVersion(projectUuid: string, trainingVersion: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Training>>;
    public startTrainingByVersion(projectUuid: string, trainingVersion: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (projectUuid === null || projectUuid === undefined) {
            throw new Error('Required parameter projectUuid was null or undefined when calling startTrainingByVersion.');
        }
        if (trainingVersion === null || trainingVersion === undefined) {
            throw new Error('Required parameter trainingVersion was null or undefined when calling startTrainingByVersion.');
        }

        let headers = this.defaultHeaders;

        // authentication (oauth) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.post<Training>(`${this.configuration.basePath}/project/${encodeURIComponent(String(projectUuid))}/training/${encodeURIComponent(String(trainingVersion))}`,
            null,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
