/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { AcousticModelType } from './acousticModelType';
import { Language } from './language';


export interface AcousticModel { 
    id?: number;
    name: string;
    language: Language;
    modelType: AcousticModelType;
}