/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type AcousticModelType = 100 | 200 | 300;

export const AcousticModelType = {
    NUMBER_100: 100 as AcousticModelType,
    NUMBER_200: 200 as AcousticModelType,
    NUMBER_300: 300 as AcousticModelType
};