/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AudioStatus } from './audioStatus';


export interface Audio { 
    uuid: string;
    name: string;
    creation_timestamp?: Date;
    status: AudioStatus;
}

