/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CallbackMethod = 0 | 1;

export const CallbackMethod = {
    GET: 0 as CallbackMethod,
    POST: 1 as CallbackMethod
};
