/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DecodeAudio } from './decodeAudio';
import { DecodeSessionStatus } from './decodeSessionStatus';


export interface DecodeSession { 
    session_uuid?: string;
    creation_timestamp?: Date;
    status?: DecodeSessionStatus;
    decodings?: Array<DecodeAudio>;
}

