/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type FileStatus = 0 | 1 | 9 | 10 | 11 | 12 | 13;

export const FileStatus = {
    NUMBER_0: 0 as FileStatus,
    NUMBER_1: 1 as FileStatus,
    NUMBER_9: 9 as FileStatus,
    NUMBER_10: 10 as FileStatus,
    NUMBER_11: 11 as FileStatus,
    NUMBER_12: 12 as FileStatus,
    NUMBER_13: 13 as FileStatus
};