/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuth2Client { 
    /**
     * Readable name for OAuth2 client
     */
    client_name: string;
    /**
     * URI for OAuth2 client
     */
    client_uri: object;
    /**
     * OAuth2 client id
     */
    client_id?: string;
    /**
     * OAuth2 client secret
     */
    client_secret?: string;
    /**
     * OAuth2 redirect URI
     */
    redirect_uri?: string;
    /**
     * OAuth2 grant type
     */
    grant_type: Array<string>;
    /**
     * Granted OAuth2 scopes
     */
    scopes: Array<string>;
    /**
     * When the OAuth2 client has been issued
     */
    issued_at?: Date;
    /**
     * When the OAuth2 client expires
     */
    expires_at?: Date;
}

