/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface OAuth2Client { 
    /**
     * Readable name for OAuth2 client
     */
    clientName: string;
    /**
     * URI for OAuth2 client
     */
    clientUri: object;
    /**
     * OAuth2 client id
     */
    clientId?: string;
    /**
     * OAuth2 client secret
     */
    clientSecret?: string;
    /**
     * OAuth2 redirect URI
     */
    redirectUri?: string;
    /**
     * OAuth2 grant type
     */
    grantType: Array<string>;
    /**
     * Granted OAuth2 scopes
     */
    scopes: Array<string>;
    /**
     * When the OAuth2 client has been issued
     */
    issuedAt?: Date;
    /**
     * When the OAuth2 client expires
     */
    expiresAt?: Date;
}

