/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TrainingStatus = 100 | 200 | 210 | 220 | 300 | 320;

export const TrainingStatus = {
    NUMBER_100: 100 as TrainingStatus,
    NUMBER_200: 200 as TrainingStatus,
    NUMBER_210: 210 as TrainingStatus,
    NUMBER_220: 220 as TrainingStatus,
    NUMBER_300: 300 as TrainingStatus,
    NUMBER_320: 320 as TrainingStatus
};