/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TrainingStats { 
    /**
     * The number of unique words
     */
    unique_words_count?: number;
    /**
     * The total number words
     */
    total_words_count?: number;
    /**
     * The number of processed lines
     */
    lines_count?: number;
    /**
     * The number of processed files
     */
    files_count?: number;
}

