/**
 * Kaldi Customization Server
 * Kaldi Customization Server.
 *
 * The version of the OpenAPI document: 1.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TrainingStatus = 100 | 150 | 151 | 200 | 205 | 206 | 207 | 208 | 210 | 220 | 300 | 320;

export const TrainingStatus = {
    Init: 100 as TrainingStatus,
    TextPrep_Pending: 150 as TrainingStatus,
    TextPrep_Failure: 151 as TrainingStatus,
    Trainable: 200 as TrainingStatus,
    Training_DataPrep_Pending: 205 as TrainingStatus,
    Training_DataPrep_InProgress: 206 as TrainingStatus,
    Training_DataPrep_Success: 207 as TrainingStatus,
    Training_DataPrep_Failure: 208 as TrainingStatus,
    Training_Pending: 210 as TrainingStatus,
    Training_In_Progress: 220 as TrainingStatus,
    Training_Success: 300 as TrainingStatus,
    Training_Failure: 320 as TrainingStatus
};
