# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.decode_api import DecodeApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDecodeApi(unittest.TestCase):
    """DecodeApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.decode_api.DecodeApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_audio_to_current_session(self):
        """Test case for assign_audio_to_current_session

        Assign Audio to decoding session  # noqa: E501
        """
        pass

    def test_create_decode_session(self):
        """Test case for create_decode_session

        Create a new decoding session  # noqa: E501
        """
        pass

    def test_delete_audio_by_uuid(self):
        """Test case for delete_audio_by_uuid

        Delete audio by UUID  # noqa: E501
        """
        pass

    def test_delete_decode_session(self):
        """Test case for delete_decode_session

        Delete the decoding session  # noqa: E501
        """
        pass

    def test_get_all_audio(self):
        """Test case for get_all_audio

        Returns a list of available audio  # noqa: E501
        """
        pass

    def test_get_all_decode_sessions(self):
        """Test case for get_all_decode_sessions

        Get the all sessions  # noqa: E501
        """
        pass

    def test_get_audio_by_uuid(self):
        """Test case for get_audio_by_uuid

        Find audio by UUID  # noqa: E501
        """
        pass

    def test_get_audio_data(self):
        """Test case for get_audio_data

        Returns the audio content  # noqa: E501
        """
        pass

    def test_get_current_decode_session(self):
        """Test case for get_current_decode_session

        Get the current session  # noqa: E501
        """
        pass

    def test_get_decode_result(self):
        """Test case for get_decode_result

        Get the result of a decoding task  # noqa: E501
        """
        pass

    def test_get_decode_session(self):
        """Test case for get_decode_session

        Get a decode session  # noqa: E501
        """
        pass

    def test_get_decodings(self):
        """Test case for get_decodings

        List of all decodings  # noqa: E501
        """
        pass

    def test_start_decode(self):
        """Test case for start_decode

        Commits the decode session for decoding  # noqa: E501
        """
        pass

    def test_unassign_audio_to_current_session(self):
        """Test case for unassign_audio_to_current_session

        Unassign Audio to decoding session  # noqa: E501
        """
        pass

    def test_upload_audio(self):
        """Test case for upload_audio

        Uploads audio  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
