# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.global_api import GlobalApi  # noqa: E501
from openapi_client.rest import ApiException


class TestGlobalApi(unittest.TestCase):
    """GlobalApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.global_api.GlobalApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_download_acoustic_model(self):
        """Test case for download_acoustic_model

        Returns the acoustic model  # noqa: E501
        """
        pass

    def test_get_acoustic_models(self):
        """Test case for get_acoustic_models

        Returns a list of available acoustic models  # noqa: E501
        """
        pass

    def test_get_languages(self):
        """Test case for get_languages

        Returns a list of available languages  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
