# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.audio_status import AudioStatus  # noqa: E501
from openapi_client.rest import ApiException


class TestAudioStatus(unittest.TestCase):
    """AudioStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAudioStatus(self):
        """Test AudioStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.audio_status.AudioStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
