# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.decoding_status import DecodingStatus  # noqa: E501
from openapi_client.rest import ApiException


class TestDecodingStatus(unittest.TestCase):
    """DecodingStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDecodingStatus(self):
        """Test DecodingStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.decoding_status.DecodingStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
