# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.resource_api import ResourceApi  # noqa: E501
from openapi_client.rest import ApiException


class TestResourceApi(unittest.TestCase):
    """ResourceApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.resource_api.ResourceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_assign_resource_to_training(self):
        """Test case for assign_resource_to_training

        Assign a resource to the training  # noqa: E501
        """
        pass

    def test_create_resource(self):
        """Test case for create_resource

        Create/Upload a new resource  # noqa: E501
        """
        pass

    def test_delete_assigned_resource_from_training(self):
        """Test case for delete_assigned_resource_from_training

        Remove a resource from the training  # noqa: E501
        """
        pass

    def test_get_corpus_of_training_resource(self):
        """Test case for get_corpus_of_training_resource

        Get the corpus of the resource  # noqa: E501
        """
        pass

    def test_get_resource(self):
        """Test case for get_resource

        Returns a list of available resources  # noqa: E501
        """
        pass

    def test_get_resource_by_uuid(self):
        """Test case for get_resource_by_uuid

        Find resource by UUID  # noqa: E501
        """
        pass

    def test_get_resource_data(self):
        """Test case for get_resource_data

        Returns the resource content  # noqa: E501
        """
        pass

    def test_set_corpus_of_training_resource(self):
        """Test case for set_corpus_of_training_resource

        Set the corpus of the resource  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
