# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.1.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.models.decode_audio import DecodeAudio  # noqa: E501
from openapi_client.rest import ApiException


class TestDecodeAudio(unittest.TestCase):
    """DecodeAudio unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDecodeAudio(self):
        """Test DecodeAudio"""
        # FIXME: construct object with mandatory attributes with example values
        # model = openapi_client.models.decode_audio.DecodeAudio()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
