# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.audio_status import AudioStatus
from openapi_server import util

from openapi_server.models.audio_status import AudioStatus  # noqa: E501

class Audio(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, name=None, creation_timestamp=None, status=None):  # noqa: E501
        """Audio - a model defined in OpenAPI

        :param uuid: The uuid of this Audio.  # noqa: E501
        :type uuid: str
        :param name: The name of this Audio.  # noqa: E501
        :type name: str
        :param creation_timestamp: The creation_timestamp of this Audio.  # noqa: E501
        :type creation_timestamp: datetime
        :param status: The status of this Audio.  # noqa: E501
        :type status: AudioStatus
        """
        self.openapi_types = {
            'uuid': str,
            'name': str,
            'creation_timestamp': datetime,
            'status': AudioStatus
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'name': 'name',
            'creation_timestamp': 'creation_timestamp',
            'status': 'status'
        }

        self._uuid = uuid
        self._name = name
        self._creation_timestamp = creation_timestamp
        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'Audio':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Audio of this Audio.  # noqa: E501
        :rtype: Audio
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        """Gets the uuid of this Audio.


        :return: The uuid of this Audio.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Audio.


        :param uuid: The uuid of this Audio.
        :type uuid: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this Audio.


        :return: The name of this Audio.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Audio.


        :param name: The name of this Audio.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def creation_timestamp(self):
        """Gets the creation_timestamp of this Audio.


        :return: The creation_timestamp of this Audio.
        :rtype: datetime
        """
        return self._creation_timestamp

    @creation_timestamp.setter
    def creation_timestamp(self, creation_timestamp):
        """Sets the creation_timestamp of this Audio.


        :param creation_timestamp: The creation_timestamp of this Audio.
        :type creation_timestamp: datetime
        """

        self._creation_timestamp = creation_timestamp

    @property
    def status(self):
        """Gets the status of this Audio.


        :return: The status of this Audio.
        :rtype: AudioStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Audio.


        :param status: The status of this Audio.
        :type status: AudioStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status
