# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DecodeSessionStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    Init = "100"
    Decoding_Pending = "150"
    Decoding_InProgress = "200"
    Decoding_Success = "300"
    Decoding_Failure = "320"

    def __init__(self):  # noqa: E501
        """DecodeSessionStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DecodeSessionStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DecodeSessionStatus of this DecodeSessionStatus.  # noqa: E501
        :rtype: DecodeSessionStatus
        """
        return util.deserialize_model(dikt, cls)
