# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class DecodeStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    Assigned = "100"
    Enqueued = "150"
    InProgress = "200"
    Success = "300"
    Failure = "320"

    def __init__(self):  # noqa: E501
        """DecodeStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'DecodeStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DecodeStatus of this DecodeStatus.  # noqa: E501
        :rtype: DecodeStatus
        """
        return util.deserialize_model(dikt, cls)
