# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.audio import Audio
from openapi_server.models.decoding_status import DecodingStatus
from openapi_server import util

from openapi_server.models.audio import Audio  # noqa: E501
from openapi_server.models.decoding_status import DecodingStatus  # noqa: E501

class Decoding(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, uuid=None, status=None, transcripts=None, audio=None):  # noqa: E501
        """Decoding - a model defined in OpenAPI

        :param uuid: The uuid of this Decoding.  # noqa: E501
        :type uuid: str
        :param status: The status of this Decoding.  # noqa: E501
        :type status: DecodingStatus
        :param transcripts: The transcripts of this Decoding.  # noqa: E501
        :type transcripts: List[object]
        :param audio: The audio of this Decoding.  # noqa: E501
        :type audio: Audio
        """
        self.openapi_types = {
            'uuid': str,
            'status': DecodingStatus,
            'transcripts': List[object],
            'audio': Audio
        }

        self.attribute_map = {
            'uuid': 'uuid',
            'status': 'status',
            'transcripts': 'transcripts',
            'audio': 'audio'
        }

        self._uuid = uuid
        self._status = status
        self._transcripts = transcripts
        self._audio = audio

    @classmethod
    def from_dict(cls, dikt) -> 'Decoding':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Decoding of this Decoding.  # noqa: E501
        :rtype: Decoding
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self):
        """Gets the uuid of this Decoding.


        :return: The uuid of this Decoding.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this Decoding.


        :param uuid: The uuid of this Decoding.
        :type uuid: str
        """
        if uuid is None:
            raise ValueError("Invalid value for `uuid`, must not be `None`")  # noqa: E501

        self._uuid = uuid

    @property
    def status(self):
        """Gets the status of this Decoding.


        :return: The status of this Decoding.
        :rtype: DecodingStatus
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this Decoding.


        :param status: The status of this Decoding.
        :type status: DecodingStatus
        """
        if status is None:
            raise ValueError("Invalid value for `status`, must not be `None`")  # noqa: E501

        self._status = status

    @property
    def transcripts(self):
        """Gets the transcripts of this Decoding.


        :return: The transcripts of this Decoding.
        :rtype: List[object]
        """
        return self._transcripts

    @transcripts.setter
    def transcripts(self, transcripts):
        """Sets the transcripts of this Decoding.


        :param transcripts: The transcripts of this Decoding.
        :type transcripts: List[object]
        """
        if transcripts is None:
            raise ValueError("Invalid value for `transcripts`, must not be `None`")  # noqa: E501

        self._transcripts = transcripts

    @property
    def audio(self):
        """Gets the audio of this Decoding.


        :return: The audio of this Decoding.
        :rtype: Audio
        """
        return self._audio

    @audio.setter
    def audio(self, audio):
        """Sets the audio of this Decoding.


        :param audio: The audio of this Decoding.
        :type audio: Audio
        """
        if audio is None:
            raise ValueError("Invalid value for `audio`, must not be `None`")  # noqa: E501

        self._audio = audio
