# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ResourceStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    Upload_InProgress = "100"
    Upload_Failure = "190"
    Preparable = "200"
    TextPrep_Enqueued = "210"
    TextPrep_InProcess = "220"
    TextPrep_Failure = "230"
    Trainable = "300"

    def __init__(self):  # noqa: E501
        """ResourceStatus - a model defined in OpenAPI

        """
        self.openapi_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'ResourceStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ResourceStatus of this ResourceStatus.  # noqa: E501
        :rtype: ResourceStatus
        """
        return util.deserialize_model(dikt, cls)
