# coding: utf-8

"""
    Kaldi Customization Server

    Kaldi Customization Server.  # noqa: E501

    The version of the OpenAPI document: 1.0.2
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DecodeMessage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'uuid': 'str',
        'transcripts': 'list[object]'
    }

    attribute_map = {
        'uuid': 'uuid',
        'transcripts': 'transcripts'
    }

    def __init__(self, uuid=None, transcripts=None):  # noqa: E501
        """DecodeMessage - a model defined in OpenAPI"""  # noqa: E501

        self._uuid = None
        self._transcripts = None
        self.discriminator = None

        if uuid is not None:
            self.uuid = uuid
        if transcripts is not None:
            self.transcripts = transcripts

    @property
    def uuid(self):
        """Gets the uuid of this DecodeMessage.  # noqa: E501


        :return: The uuid of this DecodeMessage.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this DecodeMessage.


        :param uuid: The uuid of this DecodeMessage.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def transcripts(self):
        """Gets the transcripts of this DecodeMessage.  # noqa: E501


        :return: The transcripts of this DecodeMessage.  # noqa: E501
        :rtype: list[object]
        """
        return self._transcripts

    @transcripts.setter
    def transcripts(self, transcripts):
        """Sets the transcripts of this DecodeMessage.


        :param transcripts: The transcripts of this DecodeMessage.  # noqa: E501
        :type: list[object]
        """

        self._transcripts = transcripts

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DecodeMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
